/**
 * Location blurbs — the "why is this place a big deal?" write-ups shown on the
 * end-of-day recap (DayRecap). Pure helpers + one best-effort fetch.
 *
 * Storage: a per-city SIDECAR file, `public/blurbs.<cityId>.json`, keyed by
 * location id — deliberately NOT a field on the `Location` rows in
 * `locations.<city>.json`. Reasons:
 *  - The dataset is regenerated by the pipeline (`apply-difficulty.mjs`
 *    rewrites every row in canonical field order); a sidecar can't be dropped
 *    by a re-run and never needs the pipeline to know about it.
 *  - It's loaded lazily, only when a player opens the recap, so the prose for
 *    hundreds of places never lands in the initial dataset fetch.
 *  - Rollout is incremental: a missing file (404) or a missing id both resolve
 *    to `BLURB_PLACEHOLDER`, so the recap map works for every city today and a
 *    city "gets" blurbs simply by adding entries to its sidecar.
 *
 * Sourcing: blurbs are researched via web/LLM lookups (Wikipedia, local press,
 * the venue's own site), NOT the paid Google Places API — see
 * docs/DATA-SOURCING.md §4f. Each entry may carry `sources` URLs for the
 * "read more" links; keep the text to ~1–3 sentences and player-facing.
 */

import type { LocationCategory } from '../types'
import { log } from './log'

/** Schema version of `public/blurbs.<city>.json`. Bump on breaking changes. */
export const BLURBS_FILE_VERSION = 1

export interface Blurb {
  /** 1–3 player-facing sentences: why it's famous / a fun fact. Plain text. */
  text: string
  /** Optional "read more" URLs (rendered as links, so keep them https). */
  sources?: string[]
}

export interface BlurbsFile {
  version: number
  /** City id from cities.json, for a sanity check against the file name. */
  city: string
  /** Keyed by `Location.id` (stable within the city). */
  blurbs: Record<string, Blurb>
}

/** What a resolved blurb looks like to the UI — never undefined/null. */
export interface ResolvedBlurb {
  text: string
  sources: string[]
  /** True when nothing is written for this spot yet (rollout placeholder). */
  placeholder: boolean
}

/**
 * Shown for any location without a written blurb. Wording is intentional
 * (owner, 2026-09-04): it tells the player the feature exists and just hasn't
 * reached this spot yet — the map/recap still work for every location.
 */
export const BLURB_PLACEHOLDER =
  'Write-ups haven’t rolled out for this spot yet — check back soon.'

/**
 * Pure: the blurb to show for `id`, with the placeholder when the file is
 * missing (null), the id is absent, or the text is blank.
 */
export function resolveBlurb(
  file: BlurbsFile | null,
  id: string,
): ResolvedBlurb {
  const entry = file?.blurbs[id]
  if (!entry || entry.text.trim() === '') {
    return { text: BLURB_PLACEHOLDER, sources: [], placeholder: true }
  }
  return { text: entry.text, sources: entry.sources ?? [], placeholder: false }
}

/**
 * Pure: validate an untrusted JSON value as a BlurbsFile; null if malformed.
 * Strict on shape so a typo in the hand-edited sidecar can't crash the recap —
 * a bad file degrades to "all placeholders" (and a warning in the logs).
 */
export function parseBlurbsFile(raw: unknown): BlurbsFile | null {
  if (typeof raw !== 'object' || raw === null) return null
  const o = raw as Record<string, unknown>
  if (o.version !== BLURBS_FILE_VERSION) return null
  if (typeof o.city !== 'string') return null
  if (typeof o.blurbs !== 'object' || o.blurbs === null) return null
  const blurbs: Record<string, Blurb> = {}
  for (const [id, v] of Object.entries(o.blurbs as Record<string, unknown>)) {
    if (typeof v !== 'object' || v === null) return null
    const e = v as Record<string, unknown>
    if (typeof e.text !== 'string') return null
    if (e.sources !== undefined) {
      if (
        !Array.isArray(e.sources) ||
        !e.sources.every((s) => typeof s === 'string')
      )
        return null
    }
    blurbs[id] = { text: e.text, ...(e.sources ? { sources: e.sources } : {}) }
  }
  return { version: o.version, city: o.city, blurbs }
}

/**
 * Path to a city's blurb sidecar. Same shape as `cityDataUrl`: a stable
 * filename (so it's in `public/_headers` as no-cache) plus a per-deploy
 * `?v=<build hash>` so a cached copy can't outlive the deploy that wrote it.
 */
export function blurbsUrl(cityId: string): string {
  const v = import.meta.env.VITE_BUILD_HASH ?? 'dev'
  return import.meta.env.BASE_URL + `blurbs.${cityId}.json?v=${v}`
}

/**
 * Best-effort load of a city's blurbs. Resolves to null on 404 (no sidecar for
 * this city yet), network failure, or a malformed file — NEVER throws, so the
 * recap always renders (with placeholders). Failures are logged so a broken
 * sidecar is diagnosable from kycDumpLogs.
 */
export async function fetchBlurbs(cityId: string): Promise<BlurbsFile | null> {
  const url = blurbsUrl(cityId)
  try {
    const r = await fetch(url)
    if (r.status === 404) {
      log.info('Blurbs', 'no blurbs file for city yet', { cityId })
      return null
    }
    if (!r.ok) {
      log.warn('Blurbs', 'blurbs fetch failed', { cityId, status: r.status })
      return null
    }
    const parsed = parseBlurbsFile(await r.json())
    if (!parsed) log.warn('Blurbs', 'malformed blurbs file', { cityId, url })
    else
      log.info('Blurbs', 'loaded blurbs', {
        cityId,
        count: Object.keys(parsed.blurbs).length,
      })
    return parsed
  } catch (e) {
    log.warn('Blurbs', 'blurbs fetch threw', { cityId, error: String(e) })
    return null
  }
}

const CATEGORY_LABELS: Record<LocationCategory, string> = {
  attraction: '🎡 Attraction',
  museum: '🏛️ Museum',
  park: '🏞️ Park',
  landmark: '🗿 Landmark',
  restaurant: '🍽️ Restaurant',
  bar: '🍺 Bar',
  cafe: '☕ Café',
  golf_course: '⛳ Golf course',
  plaza: '⛲ Plaza',
  venue: '🎭 Venue',
  other: '📍 Place',
}

/** Pure: human label (with emoji) for a location category, for the recap card. */
export function categoryLabel(category: LocationCategory): string {
  return CATEGORY_LABELS[category] ?? CATEGORY_LABELS.other
}
